CC = gcc
#---------------------注
# test_InsertSort.c 一定要放到第二位。。要不然会提示
# 找不到InsertSort
test_InsertSort :  test_InsertSort.c
	$(CC) test_InsertSort.c -L/home/tenywen/my_work/Algorithm/lib -lInsertSort -o test_InsertSort
 
